import { DefaultProviders } from '@/components/default-providers'
import './globals.css'

import { Header } from '@/components/header'
import { FilterContextProvider } from '@/contexts/filter-context'
import { Saira } from 'next/font/google'


const saira = Saira({ subsets: ['latin'], weight: ['300', '400', '500', '600'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <DefaultProviders>
          <Header />
          {children}
        </DefaultProviders>
      </body>
    </html>
  )
}
